Login UI
DrivenIIDevelop/Pokemon pull request #21
Opened 2024-04-28 16:30 UTC by DRD161

- Add landing page route/component
- Remove min-height from parent container. Replace with height.
- Remove background-color from parent container. Add to body element in css.
- Add mui-image types.
- Add landing page image.
- Add font sizes for h1 and h2 to theme

2024-04-28 16:42 UTC, bkeys818 requested changes

2024-04-28 16:42 UTC, bkeys818 commented on client/package.json
> +    "@types/mui-image": "^1.0.5",
Make sure to install `@types/mui-image` as a dev dependency.

2024-04-28 16:42 UTC, bkeys818 commented on client/src/routes/home/index.tsx
Looks amazing! Let's move this to `src/routes/index.tsx`. You can completely replace all the code there.

2024-04-28 21:00 UTC, DRD161 commented on client/src/routes/home/index.tsx
Good to go!

2024-04-29 01:53 UTC, bkeys818 approved these changes

2024-04-29 01:54 UTC, merged